//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nextlabs.SPSecurityTrimming.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPSecurityTrimming {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPSecurityTrimming() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nextlabs.SPSecurityTrimming.Resources.SPSecurityTrimming", typeof(SPSecurityTrimming).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate list trimming feature for all lists under current Site Collection..
        /// </summary>
        internal static string ActivateAllListTrimmingBtnLabel {
            get {
                return ResourceManager.GetString("ActivateAllListTrimmingBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancelLabel {
            get {
                return ResourceManager.GetString("BtnCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BtnOKLabel {
            get {
                return ResourceManager.GetString("BtnOKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate list trimming feature for all lists under current Site Collection..
        /// </summary>
        internal static string DeactivateAllListTrimmingBtnLabel {
            get {
                return ResourceManager.GetString("DeactivateAllListTrimmingBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Security Trimming automatically hides webparts, menus or list items that the user has no permission to access on a page. Click on the Enable butten to enable this feature for the current Site Collection..
        /// </summary>
        internal static string DisabledDescription {
            get {
                return ResourceManager.GetString("DisabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For performance reasons only enable List Trimming for lists and document libraries where it is required..
        /// </summary>
        internal static string EnableAllListTrimmingHelp {
            get {
                return ResourceManager.GetString("EnableAllListTrimmingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable list trimming for lists in the current Site Collection..
        /// </summary>
        internal static string EnableAllListTrimmingText {
            get {
                return ResourceManager.GetString("EnableAllListTrimmingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Security Trimming automatically hides webparts, menus or list items that the user has no permission to access on a page.  The feature is ENABLED for the current Site Collection. Click on the Disable butten to disable this feature for the current Site Collection..
        /// </summary>
        internal static string EnabledDescription {
            get {
                return ResourceManager.GetString("EnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate List Trimming.
        /// </summary>
        internal static string EnableListTrimmingText {
            get {
                return ResourceManager.GetString("EnableListTrimmingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Security Trimming for current Site Collection..
        /// </summary>
        internal static string EnableSecurityTrimmingText {
            get {
                return ResourceManager.GetString("EnableSecurityTrimmingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint List Trimming automatically hides all list items that the user has no permission to access in a list or document library..
        /// </summary>
        internal static string ListTrimmingDescription {
            get {
                return ResourceManager.GetString("ListTrimmingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entitlement Manager SharePoint List Trimming Settings.
        /// </summary>
        internal static string ListTrimmingPageTitle {
            get {
                return ResourceManager.GetString("ListTrimmingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Trimming.
        /// </summary>
        internal static string ListTrimmingSectionTitle {
            get {
                return ResourceManager.GetString("ListTrimmingSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Security Trimming automatically hides webparts, site menus or tree views that the user has no permission to access on a page..
        /// </summary>
        internal static string SecuritySettingDescription {
            get {
                return ResourceManager.GetString("SecuritySettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information about this feature please refer to the Nextlabs Entitlement Manager Product Documentation..
        /// </summary>
        internal static string SecuritySettingHelp {
            get {
                return ResourceManager.GetString("SecuritySettingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entitlement Manager SharePoint Security Trimming Settings.
        /// </summary>
        internal static string SecuritySettingPageTitle {
            get {
                return ResourceManager.GetString("SecuritySettingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Security Trimming.
        /// </summary>
        internal static string SecuritySettingSectionTitle {
            get {
                return ResourceManager.GetString("SecuritySettingSectionTitle", resourceCulture);
            }
        }
    }
}
