//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.nextlabs.com/configurationSchema")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.nextlabs.com/configurationSchema", IsNullable=false)]
public partial class Configuration {
    
    private SPEConfigiguration sPEConfigurationField;
    
    /// <remarks/>
    public SPEConfigiguration SPEConfiguration {
        get {
            return this.sPEConfigurationField;
        }
        set {
            this.sPEConfigurationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nextlabs.com/configurationSchema")]
public partial class SPEConfigiguration {
    
    private SPEPropertyBag[] propertyBagField;
    
    private SPEUserAttribute userAttributeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PropertyBag")]
    public SPEPropertyBag[] PropertyBag {
        get {
            return this.propertyBagField;
        }
        set {
            this.propertyBagField = value;
        }
    }
    
    /// <remarks/>
    public SPEUserAttribute UserAttribute {
        get {
            return this.userAttributeField;
        }
        set {
            this.userAttributeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nextlabs.com/configurationSchema")]
public partial class SPEPropertyBag {
    
    private SPEProperty[] propertyField;
    
    private bool disabledField;
    
    private bool disabledFieldSpecified;
    
    private SPEPropertyBagLevel levelField;
    
    private bool levelFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Property")]
    public SPEProperty[] Property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool disabled {
        get {
            return this.disabledField;
        }
        set {
            this.disabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool disabledSpecified {
        get {
            return this.disabledFieldSpecified;
        }
        set {
            this.disabledFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SPEPropertyBagLevel level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool levelSpecified {
        get {
            return this.levelFieldSpecified;
        }
        set {
            this.levelFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nextlabs.com/configurationSchema")]
public partial class SPEProperty {
    
    private bool disabledField;
    
    private bool disabledFieldSpecified;
    
    private string nameField;
    
    private string attributenameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool disabled {
        get {
            return this.disabledField;
        }
        set {
            this.disabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool disabledSpecified {
        get {
            return this.disabledFieldSpecified;
        }
        set {
            this.disabledFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string attributename {
        get {
            return this.attributenameField;
        }
        set {
            this.attributenameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nextlabs.com/configurationSchema")]
public partial class SPEUserProfileProperty {
    
    private SPEProperty[] propertyField;
    
    private bool disabledField;
    
    private bool disabledFieldSpecified;
    
    private double cachetimeoutField;
    
    private bool cachetimeoutFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Property")]
    public SPEProperty[] Property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool disabled {
        get {
            return this.disabledField;
        }
        set {
            this.disabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool disabledSpecified {
        get {
            return this.disabledFieldSpecified;
        }
        set {
            this.disabledFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cachetimeout {
        get {
            return this.cachetimeoutField.ToString();
        }
        set {
            if (string.IsNullOrEmpty(value))
            {
                this.cachetimeoutField = 0;
            }
            else
            {
                if (!double.TryParse(value, out this.cachetimeoutField))
                {
                    this.cachetimeoutField = 0;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cachetimeoutSpecified {
        get {
            return this.cachetimeoutFieldSpecified;
        }
        set {
            this.cachetimeoutFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nextlabs.com/configurationSchema")]
public partial class SPEClaim {
    
    private string nameField;
    
    private string attributenameField;
    
    private string claimtypeField;
    
    private string prefixField;
    
    private bool disabledField;
    
    private bool disabledFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string attributename {
        get {
            return this.attributenameField;
        }
        set {
            this.attributenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string claimtype {
        get {
            return this.claimtypeField;
        }
        set {
            this.claimtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool disabled {
        get {
            return this.disabledField;
        }
        set {
            this.disabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool disabledSpecified {
        get {
            return this.disabledFieldSpecified;
        }
        set {
            this.disabledFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nextlabs.com/configurationSchema")]
public partial class SPEClaims {
    
    private SPEClaim[] claimField;
    
    private bool disabledField;
    
    private bool disabledFieldSpecified;

    private double cachetimeoutField;

    private bool cachetimeoutFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Claim")]
    public SPEClaim[] Claim {
        get {
            return this.claimField;
        }
        set {
            this.claimField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool disabled {
        get {
            return this.disabledField;
        }
        set {
            this.disabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool disabledSpecified {
        get {
            return this.disabledFieldSpecified;
        }
        set {
            this.disabledFieldSpecified = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cachetimeout
    {
        get
        {
            return this.cachetimeoutField.ToString();
        }
        set
        {
            if (string.IsNullOrEmpty(value))
            {
                this.cachetimeoutField = 0;
            }
            else
            {
                if (!double.TryParse(value, out this.cachetimeoutField))
                {
                    this.cachetimeoutField = 0;
                }
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cachetimeoutSpecified
    {
        get
        {
            return this.cachetimeoutFieldSpecified;
        }
        set
        {
            this.cachetimeoutFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nextlabs.com/configurationSchema")]
public partial class SPEUserAttribute {
    
    private SPEClaims claimsField;
    
    private SPEUserProfileProperty userProfileField;
    
    /// <remarks/>
    public SPEClaims Claims {
        get {
            return this.claimsField;
        }
        set {
            this.claimsField = value;
        }
    }
    
    /// <remarks/>
    public SPEUserProfileProperty UserProfile {
        get {
            return this.userProfileField;
        }
        set {
            this.userProfileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.nextlabs.com/configurationSchema")]
public enum SPEPropertyBagLevel {
    
    /// <remarks/>
    SiteCollection,
    
    /// <remarks/>
    SubSite,
}
